# Generated by Django 6.0.7 on 2026-07-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_postgresql_compat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.IntegerField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.IntegerField(db_default=1, default=1),
        ),
    ]
