# Generated by Django 6.0.7 on 2026-07-15 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_add_catalog_database_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.TextField()),
                ('dose', models.TextField()),
                ('route', models.TextField(default='Oral')),
                ('frequency', models.TextField()),
                ('duration', models.TextField(blank=True, null=True)),
                ('start_date', models.TextField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='Active')),
                ('prescribed_by', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('admission', models.ForeignKey(db_column='admission_id', on_delete=django.db.models.deletion.CASCADE, to='hospital.admission')),
            ],
            options={
                'db_table': 'inpatient_medications',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InpatientRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_date', models.TextField()),
                ('round_time', models.TextField(blank=True, null=True)),
                ('blood_pressure', models.TextField(blank=True, null=True)),
                ('temperature', models.TextField(blank=True, null=True)),
                ('pulse', models.TextField(blank=True, null=True)),
                ('respiratory_rate', models.TextField(blank=True, null=True)),
                ('spo2', models.TextField(blank=True, null=True)),
                ('clinical_observation', models.TextField()),
                ('assessment', models.TextField(blank=True, null=True)),
                ('care_plan', models.TextField(blank=True, null=True)),
                ('doctor_name', models.TextField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField()),
                ('admission', models.ForeignKey(db_column='admission_id', on_delete=django.db.models.deletion.CASCADE, to='hospital.admission')),
                ('doctor', models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.doctor')),
            ],
            options={
                'db_table': 'inpatient_rounds',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InpatientTestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.TextField()),
                ('priority', models.TextField(default='Routine')),
                ('clinical_note', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='Ordered')),
                ('ordered_by', models.TextField(blank=True, null=True)),
                ('ordered_at', models.TextField()),
                ('admission', models.ForeignKey(db_column='admission_id', on_delete=django.db.models.deletion.CASCADE, to='hospital.admission')),
                ('service', models.ForeignKey(blank=True, db_column='service_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.service')),
            ],
            options={
                'db_table': 'inpatient_test_orders',
                'ordering': ['-id'],
            },
        ),
    ]
